### PR TITLE
docs: Adding new documentation files 

### PR DESCRIPTION
**Pull request by flodet-me**
**Integrates #52 and requires resolve before closing.**

This commit adds new references and guidelines for using this repository.

Integration of this commit requires many adjustments of the
GitHub repository to be compliant with the requirements.

Further this can only be the first step, as it just provides documentation,
but lacks in depth guidelines and moves many responsibilities to the
website, which is currently not completely ready.

These changes will resolve requirements of  [OpenSSF Best Practices](https://www.bestpractices.dev/en) 
by either documenting or implementing it.

- https://github.com/FTKeV/fapra-2023/issues/1
- https://github.com/FTKeV/fapra-2023/issues/4
- https://github.com/FTKeV/fapra-2023/issues/5
- https://github.com/FTKeV/fapra-2023/issues/6
- https://github.com/FTKeV/fapra-2023/issues/18
- https://github.com/FTKeV/fapra-2023/issues/19 (partially due to bus factor)
- https://github.com/FTKeV/fapra-2023/issues/20 (partially due to requirements after achievement of standard)
- https://github.com/FTKeV/fapra-2023/issues/24
- https://github.com/FTKeV/fapra-2023/issues/25
- https://github.com/FTKeV/fapra-2023/issues/42 (partially, we need to define code guidelines in detail to fulfill)

@heutelbeck this is just the first proposition for alignment and discussion about
how the documents should be designed.

What do you think?

### CODE REVIEW

**Comment by flodet-me** [comment]
We also hadn't the opportunity to talk about [OPA](https://www.openpolicyagent.org/), which seems to tackle also the same issue, except the streaming support. I found it very difficult to find unique selling points against this product, as it is just good enough in most cases, widely adopted and owned by the renowned [CNCF](https://www.cncf.io/).

Maybe you can help me formulate the distinct value proposition of SAPL?

**Comment by flodet-me** [comment]
As discussed with @heutelbeck, we need to first resolve some questions:

- Example for an advisory report to visualize the process and reporting
- Example for usage of DCO and CLA for significant projects (who would use what? legal implications?)

**Comment by heutelbeck** [comment]
Please do not add IDE-specific files to the main repo. Put .vscode on git ignore, please. 
Thanks.
Dominic

**Comment by flodet-me** [comment]
> Please do not add IDE-specific files to the main repo. Put .vscode on git ignore, please. Thanks. Dominic

Sorry, missed removing it.

Added to gitignore and publish Pull request for review. Should include any open point we discussed last time. 

I will also show / present the results tomorrow in our regular meeting.

**Pull request merged**
