### PR TITLE
sapl-spring-data: code coverage, sonar issue, documentation 

### PR DESCRIPTION
**Pull request by RooSchoo**
## Checklist

* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran all checks which produced no new errors or warnings for my changes.
* [x] I have checked to ensure there aren't other open Pull Requests for the same update/change.

### CODE REVIEW

**Review by heutelbeck — DISMISSED** [review]

**Comment by heutelbeck** [comment]
Looks good overall. Please address the newly introduced SonarCloud issues.

**Review by heutelbeck — APPROVED** [review]

**Comment by heutelbeck** [comment]
I have already fixed a number of the SonarCloud issues. Please check the remaining ones.

**Comment by heutelbeck** [comment]
After reviewing the final two issues, I consider them real potential null pointer problems. Please resolve cleanly.

**Review by heutelbeck — CHANGES_REQUESTED** [review]
Fix potential null pointer issues.

**Comment by RooSchoo** [comment]
> Looks good overall. Please address the newly introduced SonarCloud issues.

Thank you. One issue left. It is about NullPointerException. The thing is, I check this NullPointer one method before the one which is causing the issue...

**Review by heutelbeck — APPROVED** [review]

**Comment by heutelbeck** [comment]
Thank you. Verified null check and marked as false positive. Will merge.

**Pull request merged**
