### PR TITLE
sapl-spring-data: added new module sapl-spring-data-common

### PR DESCRIPTION
**Pull request by RooSchoo**
## Checklist

* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran all checks which produced no new errors nor warnings for my changes.
* [x] I have checked to ensure there aren't other open Pull Requests for the same update/change.

### CODE REVIEW

**Comment by RooSchoo** [comment]
Der license header macht mich noch wahnsinnig. Wie finde ich heraus, welche Datei betroffen ist? Das wäre sehr hilfreich.

**Comment by heutelbeck** [comment]
Tests must be quiet.

**Review by heutelbeck — CHANGES_REQUESTED** [review]

**Comment by heutelbeck** [comment]
Hi Roman I just wanted to merge this after I applied my fixes.

**Comment by heutelbeck** [comment]
Will reopen and merge.

**Comment by heutelbeck** [comment]
Ok I see you have a new one open anyhow. Keep this closed.

**Pull request closed without merging**
