### PR TITLE
Make regex evaluate to false when left value is null

### PR DESCRIPTION
**Pull request by mkutter**
Re-enable building sapl (see https://github.com/eclipse/xtext-xtend/issues/116 for discussion)

As discussed today, this PR makes regex conditions evaluate to false when the left argument is null.
This is required for selecting policies like the one below, when resource is set to null:

```
resource =~ "/foo/.+"
```

Before, a context with resource set to null resulted in a PolicyEvaluationException. 

A test has been added to reproduce the issue (and confirm the fix).

XText dependencies seem to have broken XText projects (again) - see https://github.com/eclipse/xtext-xtend/issues/116 for discussion.

Updating the maven-xtext-plugin and adding plugin dependencies allows for building sapl-policy-engine again

### CODE REVIEW

**Comment by fsiegrist** [comment]
- The fix of the problem with regex conditions having null as left argument is fine.
- Regarding the xtext-issue, I updated the version in the reactive-sapl branch to 2.16.0 (see commit 9a14ca9ce303467fb282ed8d237df86c3b24b5e7) and could get rid of all the workaround dependencies to org.eclipse.jdt.core, org.eclipse.core.runtime, org.eclipse.equinox.common and org.eclipse.jdt.compiler.apt. Would that be an alternative for the master branch too?

**Comment by fsiegrist** [comment]
By the way: I think the equals (==) and elementOf (in) conditions have the same problem with left arguments evaluating to null as regex, don't they?

**Comment by mkutter** [comment]
> By the way: I think the equals (==) and elementOf (in) conditions have the same problem with left arguments evaluating to null as regex, don't they?

As a matter of fact they don't - I added tests to make sure they keep up their behavior.

**Comment by mkutter** [comment]
>     * Regarding the xtext-issue, I updated the version in the reactive-sapl branch to 2.16.0 (see commit [9a14ca9](https://github.com/heutelbeck/sapl-policy-engine/commit/9a14ca9ce303467fb282ed8d237df86c3b24b5e7)) and could get rid of all the workaround dependencies to org.eclipse.jdt.core, org.eclipse.core.runtime, org.eclipse.equinox.common and org.eclipse.jdt.compiler.apt. Would that be an alternative for the master branch too?

Thanks - increased version and it worked like a breeze.

**Pull request merged**
