### PR TITLE
Add SAPL Test DSL

### PR DESCRIPTION
**Pull request by adroefke**
## Description

First Pull Request to add all required changes to enable specification of unit/integration test for policies in a DSL. 
Documentation will be added afterwards and merged with the existing documentation for sapl-test and moved to sapl-test module.

## Checklist

* [ ] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran all checks which produced no new errors or warnings for my changes.
* [x] I have checked to ensure there aren't other open Pull Requests for the same update/change.

### CODE REVIEW

**Review by heutelbeck — CHANGES_REQUESTED** [review]
Please first address the issues in SonarCloud. 

Thank you.

**Comment by adroefke** [comment]
> Please first address the issues in SonarCloud.
> 
> Thank you.

@heutelbeck 
will do, for the spotbugs with fb-contrib  ... a lot of issues are raised with the following error:
grafik

each interpreter class is flagged since i use the java 17 pattern matching syntax to check the generated xText interface for the type of the concrete implementation to interpret it. The proper approach provided by fb-contrib would be:

**This method uses the instanceof operator in a series of if/else statements to differentiate blocks of code based on type. If these types are related by inheritance, it is cleaner to just define a method in the base class, and use overridden methods in these classes.**

which is no option for xText generated classes ... how should i handle this? using a typecheck and then down-casting the interface type would probably be possible but a lot worse regarding readability and avoiding boilerplate code.

**Comment by heutelbeck** [comment]
That is precisely why I went with the logic inside of the different generated type classes of XText for SAPL. 

I also do not like this type-checking for logic approach just like FBCONTRIB complains.

But it is a viable approach to do it this way. 

I put the issue in your code as "won't fix". I don't see the big added value in doing half of a rewrite because of this if the code, in essence, is pretty easy to understand.

**Comment by heutelbeck** [comment]
a) I also checked off the side effect constructor issues.
b) converts checked exception to unchecked -> @SneakyThrows if you must convert to unchecked. But see if this is necessary here first.

**Review by heutelbeck — APPROVED** [review]

**Pull request merged**
